# Generated by Django 4.2.30 on 2026-06-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('CHAMPIONSHIP', 'Championship'), ('MEET', 'Meet'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
