# Generated by Django 4.2.30 on 2026-07-02 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swimmers', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inductee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='fame/photos/')),
                ('era', models.CharField(blank=True, default='', max_length=50)),
                ('inducted_year', models.IntegerField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, default='')),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inductees', to='core.country')),
                ('swimmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hall_of_fame_entries', to='swimmers.swimmer')),
            ],
            options={
                'ordering': ['display_order', '-inducted_year'],
            },
        ),
    ]
