# Generated by Django 4.2.30 on 2026-08-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductee',
            name='category',
            field=models.CharField(choices=[('LEGEND', 'Legends'), ('OLYMPIAN', 'Olympians'), ('ARAB_WINNER', 'Arab Swim Winners')], default='LEGEND', max_length=20),
        ),
    ]
