# Generated by Django 4.2.30 on 2026-06-27 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swimmers', '0001_initial'),
        ('core', '0001_initial'),
        ('championships', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('ARAB', 'Arab'), ('NATIONAL', 'National'), ('GCC', 'GCC')], max_length=20)),
                ('time_centiseconds', models.IntegerField()),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('result_date', models.DateField()),
                ('is_new', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='core.event')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='championships.result')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='swimmers.swimmer')),
            ],
            options={
                'ordering': ['-result_date'],
            },
        ),
    ]
