# Generated by Django 4.2.30 on 2026-07-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='pool',
            field=models.CharField(choices=[('LCM', 'LCM'), ('SCM', 'SCM')], default='LCM', max_length=3),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(choices=[('ARAB', 'Arab'), ('NATIONAL', 'National'), ('GCC', 'GCC'), ('AFRICAN', 'African'), ('ASIAN', 'Asian'), ('MEDITERRANEAN', 'Mediterranean'), ('ISLAMIC', 'Islamic'), ('WORLD', 'World')], max_length=20),
        ),
    ]
