# Generated by Django 4.2.30 on 2026-07-30 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cleanup_junk_events'),
        ('records', '0002_record_pool_alter_record_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_records', to='core.country'),
        ),
        migrations.AddField(
            model_name='record',
            name='meet_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
