# Generated by Django 4.2.30 on 2026-07-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_record_country_record_meet_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['swimmer'], name='records_rec_swimmer_789d36_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['event'], name='records_rec_event_i_ef442f_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['record_type', 'pool'], name='records_rec_record__3b913f_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['event', 'record_type', 'pool'], name='records_rec_event_i_8c3988_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['is_new'], name='records_rec_is_new_4d357b_idx'),
        ),
    ]
