# Generated by Django 4.2.30 on 2026-09-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_record_records_rec_swimmer_789d36_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='age_category',
            field=models.CharField(choices=[('OPEN', 'Open'), ('U10', 'U10'), ('U11', 'U11'), ('U12', 'U12'), ('U13', 'U13'), ('U14', 'U14'), ('U15', 'U15'), ('U16', 'U16'), ('U17', 'U17'), ('U18', 'U18')], default='OPEN', max_length=10),
        ),
    ]
