# Generated by Django 4.2.30 on 2026-09-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_record_age_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='pool',
            field=models.CharField(choices=[('LCM', 'LCM'), ('SCM', 'SCM'), ('OW', 'Open Water')], default='LCM', max_length=3),
        ),
    ]
