# Generated by Django 4.2.30 on 2026-07-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='tier',
        ),
        migrations.DeleteModel(
            name='SponsorTier',
        ),
    ]
