# Generated by Django 4.2.30 on 2026-06-23 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('pool', models.CharField(choices=[('LCM', 'Long Course (50m)'), ('SCM', 'Short Course (25m)')], max_length=3)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='championships/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'classification categories',
            },
        ),
        migrations.CreateModel(
            name='SubClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_classifications', to='championships.classification')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_centiseconds', models.IntegerField(help_text='Time in centiseconds (e.g. 2190 = 21.90s)')),
                ('fina_points', models.IntegerField(blank=True, null=True)),
                ('age_at_competition', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='championships.championship')),
            ],
            options={
                'ordering': ['time_centiseconds'],
            },
        ),
    ]
