# Generated by Django 4.2.30 on 2026-06-23 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('championships', '0001_initial'),
        ('core', '0001_initial'),
        ('swimmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='core.event'),
        ),
        migrations.AddField(
            model_name='result',
            name='swimmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='swimmers.swimmer'),
        ),
        migrations.AddField(
            model_name='classification',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='championships.classificationcategory'),
        ),
        migrations.AddField(
            model_name='championship',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='championships.classification'),
        ),
        migrations.AddField(
            model_name='championship',
            name='classification_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='championships.classificationcategory'),
        ),
        migrations.AddField(
            model_name='championship',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='championships', to='core.country'),
        ),
        migrations.AddField(
            model_name='championship',
            name='sub_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='championships.subclassification'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['event', 'time_centiseconds'], name='championshi_event_i_595218_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['championship'], name='championshi_champio_7cef7f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('swimmer', 'championship', 'event')},
        ),
    ]
