# Generated by Django 4.2.30 on 2026-06-27 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0003_result_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='championships.classificationcategory'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
