# Generated by Django 4.2.30 on 2026-07-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0006_alter_result_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='policy_pdf',
            field=models.FileField(blank=True, null=True, upload_to='championships/policies/'),
        ),
        migrations.AddField(
            model_name='championship',
            name='website',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
