# Generated by Django 4.2.30 on 2026-07-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0009_add_is_hc_to_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='meet_photo',
            field=models.ImageField(blank=True, null=True, upload_to='championships/photos/'),
        ),
    ]
