# Generated by Django 4.2.30 on 2026-07-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0012_result_hc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='is_calendar_only',
            field=models.BooleanField(default=False),
        ),
    ]
