# Generated by Django 4.2.30 on 2026-07-27 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('championships', '0013_championship_is_calendar_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='championships', to='core.country'),
        ),
    ]
