# Generated by Django 4.2.30 on 2026-07-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0017_result_original_rank'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='championship',
            index=models.Index(fields=['-date'], name='championshi_date_aab91c_idx'),
        ),
        migrations.AddIndex(
            model_name='championship',
            index=models.Index(fields=['pool'], name='championshi_pool_b2f8d2_idx'),
        ),
        migrations.AddIndex(
            model_name='championship',
            index=models.Index(fields=['country'], name='championshi_country_d7a9e9_idx'),
        ),
        migrations.AddIndex(
            model_name='championship',
            index=models.Index(fields=['classification'], name='championshi_classif_828d23_idx'),
        ),
        migrations.AddIndex(
            model_name='championship',
            index=models.Index(fields=['is_calendar_only', '-date'], name='championshi_is_cale_5e2c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['swimmer'], name='championshi_swimmer_362919_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['swimmer', 'event', 'time_centiseconds'], name='championshi_swimmer_70507c_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['time_centiseconds'], name='championshi_time_ce_7403f2_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['championship', 'event'], name='championshi_champio_53b324_idx'),
        ),
    ]
