# Generated by Django 4.2.30 on 2026-08-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0018_championship_championshi_date_aab91c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='has_open_podium',
            field=models.BooleanField(default=False),
        ),
    ]
