# Generated by Django 4.2.30 on 2026-08-06 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_country_user_swimmer_user_team_alter_user_role_and_more'),
        ('championships', '0019_championship_has_open_podium'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(help_text='1-based day of the meet (Day 1 = start date)')),
                ('gender', models.CharField(choices=[('M', 'Men'), ('F', 'Women'), ('X', 'Mixed')], default='X', max_length=1)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='championships.championship')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='core.event')),
            ],
            options={
                'ordering': ['day', 'order', 'id'],
                'indexes': [models.Index(fields=['championship', 'day'], name='championshi_champio_f38d0d_idx')],
                'unique_together': {('championship', 'day', 'event', 'gender')},
            },
        ),
    ]
