# Generated by Django 4.2.30 on 2026-08-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_country_user_swimmer_user_team_alter_user_role_and_more'),
        ('championships', '0020_programitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='programitem',
            name='age_category',
            field=models.CharField(blank=True, default='', help_text='Optional age category for this line, e.g. "U14" or "13-14 years"', max_length=40),
        ),
        migrations.AddField(
            model_name='programitem',
            name='session',
            field=models.CharField(blank=True, choices=[('HEATS', 'Heats'), ('SEMIS', 'Semifinals'), ('FINALS', 'Finals')], default='', max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='programitem',
            unique_together={('championship', 'day', 'event', 'gender', 'session', 'age_category')},
        ),
    ]
