# Generated by Django 4.2.30 on 2026-08-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0021_alter_programitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='has_double_podium',
            field=models.BooleanField(default=False),
        ),
    ]
