# Generated by Django 4.2.30 on 2026-08-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0022_championship_has_double_podium'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
