# Generated by Django 4.2.30 on 2026-08-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0023_championship_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='meet_category',
            field=models.CharField(blank=True, choices=[('OPEN', 'Open'), ('AGE_GROUP', 'Age Group')], default='', max_length=10),
        ),
    ]
