# Generated by Django 4.2.30 on 2026-08-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0027_backfill_result_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='b_final_no_medals',
            field=models.BooleanField(default=False),
        ),
    ]
