# Generated by Django 4.2.30 on 2026-08-13 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0028_championship_b_final_no_medals'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(help_text='1-based day of the meet (Day 1 = start date)')),
                ('round_summary', models.CharField(blank=True, default='', help_text='Rounds detected in the file, e.g. "Heats, Finals"', max_length=120)),
                ('source', models.CharField(choices=[('PDF', 'PDF upload'), ('LINK', 'Scraped link')], default='PDF', max_length=4)),
                ('label', models.CharField(blank=True, default='', help_text='Filename or URL of the upload', max_length=255)),
                ('results_added', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='championships.championship')),
            ],
            options={
                'ordering': ['day', 'created_at'],
                'indexes': [models.Index(fields=['championship', 'day'], name='championshi_champio_a208ab_idx')],
            },
        ),
    ]
