# Generated by Django 4.2.30 on 2026-09-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_neutral_athletes'),
        ('championships', '0030_result_manually_edited'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='programitem',
            name='time_of_day',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('EVENING', 'Evening')], default='', help_text='Optional session period — morning or evening', max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='programitem',
            unique_together={('championship', 'day', 'event', 'gender', 'session', 'time_of_day', 'age_category')},
        ),
    ]
