# Generated by Django 4.2.30 on 2026-09-09 19:31

from django.db import migrations, models


def mark_existing_auto(apps, schema_editor):
    # Every program line that exists today was generated by the importer or the
    # results synthesizer — no admin has hand-entered one yet — so flag them all
    # as auto so they can be wiped and rebuilt from the source with real dates.
    ProgramItem = apps.get_model('championships', 'ProgramItem')
    ProgramItem.objects.update(is_auto=True)


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0031_alter_programitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programitem',
            name='is_auto',
            field=models.BooleanField(default=False, help_text='Generated by the importer from the source file (vs. entered by an admin). Auto lines are wiped and rebuilt on re-import; admin-entered lines are never touched.'),
        ),
        migrations.RunPython(mark_existing_auto, migrations.RunPython.noop),
    ]
