# Generated by Django 4.2.30 on 2026-09-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0032_programitem_is_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='round_type',
            field=models.CharField(blank=True, choices=[('Finals', 'Finals'), ('Semifinals', 'Semifinals'), ('Prelims', 'Prelims'), ('Heats', 'Heats'), ('Consolation', 'Consolation'), ('Swim-off', 'Swim-off'), ('Junior Final', 'Junior Final'), ('Final C', 'Final C'), ('Final D', 'Final D'), ('', 'Unknown')], default='', max_length=20),
        ),
    ]
