# Generated by Django 4.2.30 on 2026-09-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0033_add_round_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='category_gender_map',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='championship',
            name='gender_display',
            field=models.CharField(blank=True, choices=[('', 'Auto-detect'), ('men_women', 'Men / Women'), ('boys_girls', 'Boys / Girls'), ('all', 'Men / Women / Boys / Girls')], default='', max_length=12),
        ),
    ]
