# Generated by Django 4.2.30 on 2026-09-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0034_gender_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='heats_category_medals',
            field=models.BooleanField(default=False),
        ),
    ]
