# Generated by Django 4.2.30 on 2026-09-26 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0036_result_reaction_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('STARTLIST', 'Start list'), ('REPORT', 'Report')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='championships/documents/')),
                ('day', models.PositiveSmallIntegerField(blank=True, help_text='Optional 1-based meet day this document belongs to', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='championships.championship')),
            ],
            options={
                'ordering': ['kind', 'day', 'id'],
                'indexes': [models.Index(fields=['championship', 'kind'], name='championshi_champio_2d0503_idx')],
            },
        ),
    ]
