import api from './client'

export const getTeams = (params) => api.get('/teams/', { params })
export const getTeam = (id) => api.get(`/teams/${id}/`)
export const createTeam = (data) => api.post('/teams/', data, { headers: { 'Content-Type': 'multipart/form-data' } })
export const updateTeam = (id, data) => api.patch(`/teams/${id}/`, data, { headers: { 'Content-Type': 'multipart/form-data' } })
export const deleteTeam = (id) => api.delete(`/teams/${id}/`)
export const bulkDeleteTeams = (ids) => api.post('/teams/bulk-delete/', { ids })
export const getTeamProfile = (id) => api.get(`/teams/${id}/profile/`)
export const getTeamTimes = (id, params) => api.get(`/teams/${id}/times/`, { params })
export const getTeamMedals = (id) => api.get(`/teams/${id}/medals/`)
export const uploadTeamLogo = (id, formData) => api.post(`/teams/${id}/upload_logo/`, formData, { headers: { 'Content-Type': 'multipart/form-data' } })
export const uploadTeamBanner = (id, formData) => api.post(`/teams/${id}/upload_banner/`, formData, { headers: { 'Content-Type': 'multipart/form-data' } })
export const getTeamProgression = (id, params) => api.get(`/teams/${id}/progression/`, { params })
export const mergeTeams = (data) => api.post('/teams/merge/', data)
export const autoDedupeTeams = (data) => api.post('/teams/auto-dedupe/', data)
export const findDuplicateTeams = () => api.get('/teams/find-duplicates/')
export const getTeamRecords = (id) => api.get(`/teams/${id}/records/`)
export const getTeamStats = (id) => api.get(`/teams/${id}/stats/`)
export const getTeamRanking = (id) => api.get(`/teams/${id}/ranking/`)
