# Generated by Django 4.2.30 on 2026-08-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('path', models.CharField(max_length=300)),
                ('visitor', models.CharField(help_text='Anonymous long-lived browser id', max_length=64)),
                ('session', models.CharField(help_text='Anonymous per-tab-session id', max_length=64)),
                ('referrer', models.CharField(blank=True, default='', help_text='External referrer domain ("" = direct)', max_length=300)),
                ('device', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], default='desktop', max_length=10)),
                ('browser', models.CharField(blank=True, default='', max_length=30)),
                ('country', models.CharField(blank=True, default='', help_text='Visitor country from the CDN geo header, when present', max_length=64)),
                ('is_new_visitor', models.BooleanField(default=False, help_text='First page view ever from this browser')),
            ],
            options={
                'indexes': [models.Index(fields=['ts', 'path'], name='analytics_p_ts_9959f3_idx'), models.Index(fields=['ts', 'visitor'], name='analytics_p_ts_f874c8_idx'), models.Index(fields=['path'], name='analytics_p_path_3382b5_idx')],
            },
        ),
    ]
