// Single source of truth for everything the admin can hide/unhide.
// Page keys gate routes + nav links (see App.jsx / Layout.jsx).
// Dotted keys gate subfeatures: tabs on the federation, club and swimmer
// pages. A missing key means "visible" — only stored `false` hides.
// Admins always see hidden items (dimmed) so they can prepare content.

export const FEATURE_GROUPS = [
  {
    id: 'pages',
    label: 'Site Pages',
    hint: 'Hiding a page removes it from all menus and blocks its URL for visitors.',
    items: [
      ['records', 'Records'],
      ['new_records', 'New Records'],
      ['medals', 'Medals'],
      ['rankings', 'Rankings'],
      ['qualifying_times', 'Qualifying Times'],
      ['predictions', 'Predictions'],
      ['calendar', 'Calendar'],
      ['live', 'Live Results'],
      ['swimmers', 'Swimmers'],
      ['teams', 'Clubs'],
      ['academies', 'Academies'],
      ['compare', 'Compare'],
      ['coaches', 'Coaches'],
      ['hall_of_fame', 'Hall of Fame'],
      ['news', 'News'],
      ['media', 'Media'],
      ['marketplace', 'Marketplace'],
      ['lab', 'ArabSwim Lab'],
    ],
  },
  {
    id: 'fed_tabs',
    label: 'Federation Page Tabs',
    hint: 'Tabs on every federation profile. Overview cannot be hidden.',
    items: [
      ['fed.tab.news', 'News'],
      ['fed.tab.board', 'Board'],
      ['fed.tab.team', 'Team'],
      ['fed.tab.statistics', 'Statistics'],
      ['fed.tab.progression', 'Progression'],
      ['fed.tab.records', 'Records'],
      ['fed.tab.ranking', 'Ranking'],
      ['fed.tab.medals', 'Medals'],
      ['fed.tab.qualifying', 'Qualifying'],
      ['fed.tab.clubs', 'Clubs'],
      ['fed.tab.academies', 'Academies'],
      ['fed.tab.compare', 'Compare'],
      ['fed.tab.prediction', 'Prediction'],
      ['fed.tab.multimedia', 'Multimedia'],
    ],
  },
  {
    id: 'club_tabs',
    label: 'Club Page Tabs',
    hint: 'Tabs on every club/national-team profile. Overview cannot be hidden.',
    items: [
      ['club.tab.news', 'News'],
      ['club.tab.board', 'Board'],
      ['club.tab.team', 'Team'],
      ['club.tab.training', 'Training'],
      ['club.tab.statistics', 'Statistics'],
      ['club.tab.progression', 'Progression'],
      ['club.tab.records', 'Records'],
      ['club.tab.ranking', 'Ranking'],
      ['club.tab.medals', 'Medals'],
      ['club.tab.compare', 'Compare'],
      ['club.tab.prediction', 'Prediction'],
      ['club.tab.multimedia', 'Multimedia'],
    ],
  },
  {
    id: 'swimmer_tabs',
    label: 'Swimmer Profile Tabs',
    hint: 'Tabs on every swimmer profile. Overall cannot be hidden.',
    items: [
      ['swimmer.tab.times', 'Times'],
      ['swimmer.tab.meets', 'Meets'],
      ['swimmer.tab.medals', 'Medals'],
      ['swimmer.tab.rankings', 'Rankings'],
      ['swimmer.tab.records', 'Records'],
      ['swimmer.tab.qualifying', 'Qualifying'],
      ['swimmer.tab.progression', 'Progression'],
      ['swimmer.tab.compare', 'Compare'],
      ['swimmer.tab.transfers', 'Representations'],
      ['swimmer.tab.gallery', 'Gallery'],
    ],
  },
]
