# Generated by Django 4.2.30 on 2026-06-23 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('championships', '0002_initial'),
        ('swimmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal_type', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], max_length=10)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medals', to='championships.championship')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medals', to='core.event')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='championships.result')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medals', to='swimmers.swimmer')),
            ],
            options={
                'ordering': ['championship', 'event'],
            },
        ),
    ]
