# Generated by Django 4.2.30 on 2026-07-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0002_relay_medals_per_athlete'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medal',
            index=models.Index(fields=['swimmer'], name='medals_meda_swimmer_0fbaf6_idx'),
        ),
        migrations.AddIndex(
            model_name='medal',
            index=models.Index(fields=['championship'], name='medals_meda_champio_8dba41_idx'),
        ),
        migrations.AddIndex(
            model_name='medal',
            index=models.Index(fields=['medal_type'], name='medals_meda_medal_t_0f3b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='medal',
            index=models.Index(fields=['championship', 'medal_type'], name='medals_meda_champio_491fda_idx'),
        ),
    ]
