# Generated by Django 4.2.30 on 2026-08-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0003_medal_medals_meda_swimmer_0fbaf6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medal',
            name='scope',
            field=models.CharField(choices=[('CATEGORY', 'Category'), ('OPEN', 'Open')], default='CATEGORY', max_length=10),
        ),
    ]
