# Generated by Django 4.2.30 on 2026-08-12 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitefeature'),
        ('medals', '0004_medal_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='medal',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medals', to='core.country'),
        ),
    ]
