# Generated by Django 4.2.30 on 2026-07-02 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('category', models.CharField(choices=[('SUITS', 'Suits'), ('GOGGLES', 'Goggles'), ('TRAINING_GEAR', 'Training Gear'), ('APPAREL', 'Apparel'), ('ELECTRONICS', 'Electronics'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used')], default='USED', max_length=10)),
                ('seller_name', models.CharField(blank=True, default='', max_length=200)),
                ('seller_contact', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SOLD', 'Sold')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='core.country')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='market/listings/')),
                ('sort_order', models.IntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.listing')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
