# Generated by Django 4.2.30 on 2026-06-27 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swimmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('birth_year', models.IntegerField(blank=True, help_text='Year of birth when exact DOB is unknown', null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('club', models.CharField(blank=True, default='', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='swimmers/photos/')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='swimmers', to='core.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SwimmerNickname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nicknames', to='swimmers.swimmer')),
            ],
            options={
                'unique_together': {('swimmer', 'nickname')},
            },
        ),
    ]
