# Generated by Django 4.2.30 on 2026-07-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimmer',
            name='is_relay_team',
            field=models.BooleanField(default=False, help_text='Placeholder row that holds relay results for a team, not a real athlete'),
        ),
    ]
