# Generated by Django 4.2.30 on 2026-06-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimmers', '0002_delete_swimmerspecialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimmer',
            name='club',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
