# Generated by Django 4.2.30 on 2026-07-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimmers', '0002_swimmer_is_relay_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimmer',
            name='is_retired',
            field=models.BooleanField(default=False),
        ),
    ]
