# Generated by Django 4.2.30 on 2026-06-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimmers', '0003_swimmer_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimmer',
            name='birth_year',
            field=models.IntegerField(blank=True, help_text='Year of birth when exact DOB is unknown', null=True),
        ),
        migrations.AlterField(
            model_name='swimmer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
