# Generated by Django 4.2.30 on 2026-07-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimmers', '0004_nationalitychange'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimmer',
            name='facebook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='swimmer',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
