# Generated by Django 4.2.30 on 2026-07-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimmers', '0005_swimmer_facebook_url_swimmer_instagram_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='swimmer',
            index=models.Index(fields=['nationality'], name='swimmers_sw_nationa_eecdc2_idx'),
        ),
        migrations.AddIndex(
            model_name='swimmer',
            index=models.Index(fields=['sex'], name='swimmers_sw_sex_f9c696_idx'),
        ),
        migrations.AddIndex(
            model_name='swimmer',
            index=models.Index(fields=['is_relay_team'], name='swimmers_sw_is_rela_b9a02b_idx'),
        ),
        migrations.AddIndex(
            model_name='swimmer',
            index=models.Index(fields=['nationality', 'sex'], name='swimmers_sw_nationa_7845fd_idx'),
        ),
    ]
