# Generated by Django 4.2.30 on 2026-08-07 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_country_user_swimmer_user_team_alter_user_role_and_more'),
        ('swimmers', '0006_swimmer_swimmers_sw_nationa_eecdc2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimmer',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='swimmers', to='core.country'),
        ),
    ]
