# Generated by Django 4.2.30 on 2026-08-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimmers', '0007_alter_swimmer_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimmer',
            name='manually_edited',
            field=models.BooleanField(default=False, help_text='An admin hand-edited this swimmer. Re-imports must NOT overwrite edited fields (e.g. current club) — manual edits always win over the automatic pipeline.'),
        ),
    ]
