import api from './client'

export const getChampionships = (params) => api.get('/championships/', { params })
export const getChampionship = (id) => api.get(`/championships/${id}/`)
export const createChampionship = (data) => api.post('/championships/', data, { headers: { 'Content-Type': 'multipart/form-data' } })
export const updateChampionship = (id, data) => api.patch(`/championships/${id}/`, data, { headers: { 'Content-Type': 'multipart/form-data' } })
export const deleteChampionship = (id) => api.delete(`/championships/${id}/`)
export const getChampionshipResults = (id, params) => api.get(`/championships/${id}/results/`, { params })
export const getChampionshipStats = (id) => api.get(`/championships/${id}/stats/`)
export const getChampionshipCountrySwimmers = (id, countryId) => api.get(`/championships/${id}/country-swimmers/`, { params: { country: countryId } })
export const getChampionshipClubSwimmers = (id, club) => api.get(`/championships/${id}/club-swimmers/`, { params: { club } })
export const addChampionshipResult = (id, data) => api.post(`/championships/${id}/results/`, data)
export const addChampionshipResults = (id, data) => api.post(`/championships/${id}/add-results/`, data)
export const updateResult = (resultId, data) => api.patch(`/results/${resultId}/`, data)
export const deleteResult = (resultId) => api.delete(`/results/${resultId}/`)
export const uploadPdf = (id, formData) => api.post(`/championships/${id}/upload-pdf/`, formData)
export const importExcel = (id, formData) => api.post(`/championships/${id}/import-excel/`, formData)
export const getResultsBySwimmer = (id) => api.get(`/championships/${id}/results-by-swimmer/`)
export const bulkDeleteResults = (id, swimmerIds) => api.post(`/championships/${id}/bulk-delete-results/`, { swimmer_ids: swimmerIds })
export const bulkDeleteResultIds = (id, resultIds) => api.post(`/championships/${id}/bulk-delete-result-ids/`, { result_ids: resultIds })
export const getAllResults = (id) => api.get(`/championships/${id}/all-results/`)
export const getMostImproved = (id) => api.get(`/championships/${id}/most-improved/`)
export const getChampionshipComparison = (id) => api.get(`/championships/${id}/compare/`)
export const getClassificationCategories = () => api.get('/classification-categories/')
export const getClassifications = (category) => api.get('/classifications/', { params: category ? { category } : {} })
export const getSubClassifications = (classification) => api.get('/sub-classifications/', { params: { classification } })
