# Generated by Django 4.2.30 on 2026-08-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_album_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='display_size',
            field=models.CharField(choices=[('SQUARE', '1:1'), ('PORTRAIT', '4:5'), ('LANDSCAPE', '16:9'), ('ORIGINAL', 'Original')], default='SQUARE', help_text='Instagram-style display crop for gallery grids', max_length=10),
        ),
    ]
