# Generated by Django 4.2.30 on 2026-07-25 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualifyingStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Paris 2024 Olympics', max_length=200)),
                ('competition_type', models.CharField(choices=[('olympics', 'Olympics'), ('world_championships', 'World Championships')], max_length=30)),
                ('year', models.IntegerField()),
                ('qualifying_period_start', models.DateField(blank=True, null=True)),
                ('qualifying_period_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QualifyingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('cut', models.CharField(choices=[('A', 'A Standard'), ('B', 'B Standard')], max_length=1)),
                ('time_centiseconds', models.IntegerField(help_text='Qualifying time in centiseconds')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualifying_times', to='core.event')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='qualifying_times.qualifyingstandard')),
            ],
            options={
                'ordering': ['event__sort_order', 'event__distance', 'gender', 'cut'],
                'unique_together': {('standard', 'event', 'gender', 'cut')},
            },
        ),
    ]
