# Generated by Django 4.2.30 on 2026-07-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('qualifying_times', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qualifyingtime',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='qualifyingtime',
            name='pool',
            field=models.CharField(choices=[('LCM', 'Long Course (50m)'), ('SCM', 'Short Course (25m)')], default='LCM', max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='qualifyingtime',
            unique_together={('standard', 'event', 'gender', 'cut', 'pool')},
        ),
    ]
