# Generated by Django 4.2.30 on 2026-07-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifying_times', '0002_add_pool_to_qualifyingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualifyingstandard',
            name='competition_type',
            field=models.CharField(help_text='e.g. olympics, world_championships, mediterranean_games, or any custom type', max_length=100),
        ),
    ]
