# Generated by Django 4.2.30 on 2026-08-04 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, default='', help_text='e.g. President, Vice President, Secretary General, Treasurer', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teams/board/')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('bio', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_members', to='teams.team')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
