# Generated by Django 4.2.30 on 2026-09-28 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0001_initial'),
        ('teams', '0005_boardmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('coach_name', models.CharField(blank=True, default='', max_length=200)),
                ('group_name', models.CharField(blank=True, default='', help_text='Training group / squad name, e.g. First Team', max_length=200)),
                ('age_group', models.CharField(blank=True, default='', help_text='e.g. U12, 13-14, Seniors', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='academies.academy')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='teams.team')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
