# Generated by Django 4.2.30 on 2026-06-23 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('championships', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('source_format', models.CharField(max_length=50)),
                ('meet_name', models.CharField(blank=True, default='', max_length=200)),
                ('total_results', models.IntegerField(default=0)),
                ('created_swimmers', models.IntegerField(default=0)),
                ('matched_swimmers', models.IntegerField(default=0)),
                ('created_results', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('championship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='championships.championship')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
