# Generated by Django 4.2.30 on 2026-08-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('meet_name', models.CharField(blank=True, default='', max_length=255)),
                ('date_text', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('progress', models.CharField(blank=True, default='', max_length=100)),
                ('error', models.TextField(blank=True, default='')),
                ('total_events', models.IntegerField(default=0)),
                ('total_results', models.IntegerField(default=0)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
