# Generated by Django 4.2.30 on 2026-08-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_scrapejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='name_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
