# Generated by Django 4.2.30 on 2026-08-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0003_scrapejob_name_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('progress', models.CharField(blank=True, default='', max_length=200)),
                ('error', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
