# Generated by Django 4.2.30 on 2026-07-25 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='coaches/photos/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('level', models.CharField(blank=True, choices=[('HEAD', 'Head Coach'), ('ASSISTANT', 'Assistant Coach'), ('TECHNIQUE', 'Technique Coach'), ('FITNESS', 'Fitness / S&C Coach'), ('YOUTH', 'Youth Development Coach'), ('PRIVATE', 'Private Coach')], default='', max_length=20)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('current_club', models.CharField(blank=True, default='', max_length=200)),
                ('specializations', models.CharField(blank=True, default='', help_text='Comma-separated, e.g. Sprint Freestyle, Open Water, Youth', max_length=500)),
                ('certifications', models.TextField(blank=True, default='', help_text='One per line, e.g. ASCA Level 3, World Aquatics Coach Certificate')),
                ('bio', models.TextField(blank=True, default='')),
                ('achievements', models.TextField(blank=True, default='', help_text='Key coaching achievements, one per line')),
                ('cv_file', models.FileField(blank=True, help_text='PDF resume / CV', null=True, upload_to='coaches/cvs/')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('instagram', models.CharField(blank=True, default='', max_length=100)),
                ('linkedin', models.URLField(blank=True, default='')),
                ('is_available', models.BooleanField(default=True, help_text='Currently open to new opportunities')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coaches', to='core.country')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
