# Generated by Django 4.2.30 on 2026-09-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional PDF shown to readers on the article page', null=True, upload_to='news/attachments/'),
        ),
    ]
