# Generated by Django 4.2.30 on 2026-08-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_country_user_swimmer_user_team_alter_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
