# Generated by Django 4.2.30 on 2026-09-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_neutral_athletes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='stroke',
            field=models.CharField(choices=[('Freestyle', 'Freestyle'), ('Backstroke', 'Backstroke'), ('Butterfly', 'Butterfly'), ('Breaststroke', 'Breaststroke'), ('Individual Medley', 'Individual Medley'), ('Medley Relay', 'Medley Relay'), ('Freestyle Relay', 'Freestyle Relay'), ('Open Water', 'Open Water')], max_length=30),
        ),
    ]
