# Generated by Django 4.2.30 on 2026-09-22 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0001_initial'),
        ('core', '0009_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='academies.academy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ATHLETE', 'Athlete'), ('CLUB', 'Club'), ('ACADEMY', 'Academy'), ('FEDERATION', 'Federation'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=10),
        ),
    ]
