# Generated by Django 4.2.30 on 2026-09-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_academy_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='federation_address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='country',
            name='federation_email',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='country',
            name='federation_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='country',
            name='federation_tagline',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='country',
            name='federation_website',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
